apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-init-fail-
spec:
  entrypoint: entry-handling
  templates:
  - name: entry-handling
    templateRef:
      name: workflow-template-stage-template
      template: stage-template
    arguments:
      parameters:
      - name: message
        value: "This is the entry msg"
    initContainers:
    - name: initial
      steps:
      - - name: aa
          template: hello2
      - - name: ab
          template: stage
    - name: hello2
      image: alpine:latest
      command: ["exit 1"]
      mirrorVolumeMounts: true
  - name: stage
    templateRef:
      name: workflow-template-stage-template
      template: stage-template
    arguments:
      parameters:
      - name: message
        value: "hello world"
