apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-init-fail2-
spec:
  entrypoint: flow
  templates:
  - name: flow
    steps:
    - - name: init-step
        template: entry-handling
        continueOn:
          failed: true
      - name: function-step
        template: stage
  - name: entry-handling
    templateRef:
      name: workflow-template-stage-template
      template: stage-template
    arguments:
      parameters:
      - name: message
        value: "This is the entry msg"
    initContainers:
    - name: hello2
      image: alpine:latest
      command: ["exit 1"]
      mirrorVolumeMounts: true
  - name: stage
    templateRef:
      name: workflow-template-stage-template
      template: stage-template
    arguments:
      parameters:
      - name: message
        value: "hello world"
