apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-stage-
spec:
  entrypoint: stage
  templates:
  - name: stage
    templateRef:
      name: workflow-template-stage-template
      template: stage-template
    arguments:
      parameters:
      - name: message
        value: "hello world"
