apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: second-global-outputs-
spec:
  entrypoint: generate-globals
  onExit: consume-globals

  templates:
  - name: generate-globals
    steps:
    - - name: generate
        template: global-output

  # Template which produces a global parameter and artifact
  - name: global-output
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["sleep 1; echo -n second hello world > /tmp/second_hello_world.txt"]
    outputs:
      parameters:
      # export a global parameter. The parameter will be programatically available in the completed
      # workflow object under: workflow.outputs.parameters
      - name: hello-param
        valueFrom:
          path: /tmp/second_hello_world.txt
        globalName: my-global-param2
      # export a global artifact. The artifact will be programatically available in the completed
      # workflow object under: workflow.outputs.artifacts

  # Once exported, global outputs are referenceable in later parts of the workflow.
  # In this example, the consume-globals template is invoked after the generate-globals step, as
  # well as in the onExit handler. and can reference the globals, my-global-param and my-global-art.
  - name: consume-globals
    steps:
    - - name: consume-global-param
        template: consume-global-param

  - name: consume-global-param
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{workflow.outputs.parameters.my-global-param2}}"]
